### PR TITLE
Fixes Onboarding Bugs

### LINKED ISSUE #640: No Private Repo's Results In 500 Error
If you try and go through the on boarding flow, without the ability to create any private repo's on your GitHub.com account, then you get an 500 internal server error.

I'm thinking perhaps this should be changed to give the user a more friendly message?

This is the error from the console:
`Octokit::UnprocessableEntity - POST https://api.github.com/user/repos: 422 - Please upgrade your plan to create a new private repository. // See: https://github.com/pricing:`

### PR DESCRIPTION
**Pull request by AndrewMcBurney**
Closes #640, #607, #673 

### Goals
From [this comment](https://github.com/fastlane/ci/issues/640#issuecomment-380949627):

- [x] Add bot user API Token as a required environment variable
- [x] Document the need for having an API Token for the bot user
- [x] Create the repo if it doesn't exist, using the user's credentials
- [x] Use https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator to grant the bot account access
- [x] Then https://developer.github.com/v3/repos/invitations/#accept-a-repository-invitation from the bot account
- [x] Clone the repo using the bot account
- [x] Fixes session-based flash messages

### Changes

- Added methods for inviting the bot user to the configuration repository, and for accepting an invitation to the configuration repository.
- Removes the `FASTLANE_CI_USER` and `FASTLANE_CI_INITIAL_CLONE_EMAIL` environment variables, since we can obtain those values through the API tokens.
- Adds the `FASTLANE_CI_INITIAL_ONBOARDING_USER_API_TOKEN` variable which is used for creating the private remote configuration repository, and inviting the bot user to the repository so it may perform actions on it.
- Adds styled session-based flash messages

### CODE REVIEW

File: app/features/configuration/configuration_controller.rb [hunk 1]
```diff
@@ -63,8 +63,8 @@ def keys
     # @return [Set[String]]
     def post_parameter_list_for_validation
       return Set.new(
-        %w(encryption_key ci_user_email ci_user_password repo_url
-           clone_user_email clone_user_api_token)
+        %w(encryption_key ci_user_email ci_user_password ci_user_api_token
+           repo_url clone_user_email clone_user_api_token)
```
Comment (taquitos) [inline app/features/configuration/configuration_controller.rb]: maybe we need to rename things, like `clone_user_email` should actually be the bot now, iff we do the invitation dance

File: app/features/onboarding/onboarding_controller.rb [hunk 2]
```diff
@@ -91,6 +91,8 @@ class OnboardingController < ControllerBase
     # 3) If the data is not valid, display an error message
     post "#{HOME}/ci_bot_account" do
       if valid_params?(params, post_parameter_list_for_ci_bot_user_validation)
+        validate_api_token_correct(params[:ci_user_api_token].strip, "ci_bot_account")
```
Comment (taquitos) [inline app/features/onboarding/onboarding_controller.rb]: confusion between `ci_user_api_token` and `ci_bot_account`
maybe `ci_user_api_token` should be `github_bot_api_token`?

Comment (AndrewMcBurney) [reply app/features/onboarding/onboarding_controller.rb]: I like that idea 👍

File: app/features/onboarding/onboarding_controller.rb [hunk 3]
```diff
@@ -139,6 +141,8 @@ class OnboardingController < ControllerBase
 
         scope_validation_error = FastlaneCI::GitHubService.token_scope_validation_error(params[:clone_user_api_token])
         if scope_validation_error.nil?
+          validate_api_token_correct(params[:clone_user_api_token].strip, "initial_clone_user")
```
Comment (taquitos) [inline app/features/onboarding/onboarding_controller.rb]: `clone_user_api_token` and `initial_clone_user `
I think this should be the bot stuff now (when doing the invitation dance)

File: app/features/onboarding/onboarding_controller.rb [hunk 4]
```diff
@@ -207,6 +212,21 @@ class OnboardingController < ControllerBase
 
     private
 
+    #####################################################
+    # @!group Redirect Helpers
+    #####################################################
+
+    def validate_api_token_correct(api_token, route)
```
Comment (taquitos) [inline app/features/onboarding/onboarding_controller.rb]: 👍

File: app/features/onboarding/views/forms/_ci_bot_account.erb [hunk 5]
```diff
@@ -50,6 +50,30 @@
...
+      on GitHub</a> with <code>repo</code> permissions on your GitHub bot account:
+
+      <img src="../images/github_access_token.png" width="60%">
+    </li>
+
+
+    <li>Enter your bot user's API Token:</li>
+
+    <div class="mdl-textfield mdl-js-textfield">
+      <label for="input"><code>FASTLANE_CI_BOT_API_TOKEN</code></label>
```
Comment (taquitos) [inline app/features/onboarding/views/forms/_ci_bot_account.erb]: ❤️

File: app/services/configuration_repository_service.rb [hunk 6]
```diff
@@ -9,22 +9,30 @@ class ConfigurationRepositoryService
     include FastlaneCI::Logging
     include FastlaneCI::GitHubHandler
 
+    # An octokit client authenticated with the clone user's API token
+    #
+    # @return [Octokit::Client]
+    attr_reader :clone_user_client
```
Comment (taquitos) [inline app/services/configuration_repository_service.rb]: `clone_user_client` maybe should be `onboarding_user_client`?

File: app/services/configuration_repository_service.rb [hunk 7]
```diff
@@ -57,20 +65,71 @@ def configuration_repository_valid?
       return valid
     end
 
+    # Adds the bot user as a collaborator to the fastlane.ci configuration
+    # repository
+    #
+    # @return [Boolean] If the user was added successfully
+    def add_bot_user_as_collaborator
+      invitation_id = invite_bot_user_to_configuration_repository
+      return accept_invitation_to_repository_as_bot_user(invitation_id) if invitation_id
```
Comment (taquitos) [inline app/services/configuration_repository_service.rb]: what happens if we don't have an `invitation_id`?

File: app/services/configuration_repository_service.rb [hunk 8]
```diff
@@ -57,20 +65,71 @@ def configuration_repository_valid?
...
     # Returns `true` if the remote configuration repository exists
     #
     # @return [Boolean]
     def configuration_repository_exists?
       # Return cached true value, if it was successful, otherwise keep checking because it might have been fixed
       return @config_repo_exists unless @config_repo_exists.nil? || (@config_repo_exists == false)
-      github_action(client) do
-        @config_repo_exists = client.repository?(repo_shortform)
+      github_action(clone_user_client) do
+        @config_repo_exists = clone_user_client.repository?(repo_shortform)
```
Comment (taquitos) [inline app/services/configuration_repository_service.rb]: I think this should be the bot's account

File: app/shared/environment_variables.rb [hunk 9]
```diff
@@ -32,6 +33,11 @@ def ci_user_password
       ENV["FASTLANE_CI_PASSWORD"]
     end
 
+    # The API token used for the bot account
+    def ci_user_api_token
+      ENV["FASTLANE_CI_BOT_API_TOKEN"]
```
Comment (taquitos) [inline app/shared/environment_variables.rb]: make sure you add this to the `EnvironmentVariables.md` doc 👍

File: app/services/configuration_repository_service.rb (hunk 7 above)
Comment (AndrewMcBurney) [reply app/services/configuration_repository_service.rb]: It will error out [here](https://github.com/fastlane/ci/pull/661/files/791d9f1453f6cc7301e1377ae467d3dd92d2d965#diff-7f1f37a512473c728fda7e56977fbdeeR126).

Would you like me to do error handling in this method as well?

**Comment by taquitos** [comment]
Looking good, maybe it would be good to document which accounts are responsible for what. Which account checkout out the repo locally, which account adds files, and which account pushes changes 👍

File: app/services/configuration_repository_service.rb (hunk 6 above)
Comment (AndrewMcBurney) [reply app/services/configuration_repository_service.rb]: Hmm, I tried to keep it consistent with the environment variable names. Would we want to change the environment variable name then as well?

File: app/shared/environment_variables.rb (hunk 9 above)
Comment (AndrewMcBurney) [reply app/shared/environment_variables.rb]: Will do 👍

File: app/services/configuration_repository_service.rb (hunk 7 above)
Comment (taquitos) [reply app/services/configuration_repository_service.rb]: Yeah but if you get to line `74`, and there's no `invitation_id` it seems like `add_bot_user_as_collaborator` just fails silently. Only getting a log message. Maybe we should crash?

File: app/services/configuration_repository_service.rb (hunk 6 above)
Comment (taquitos) [reply app/services/configuration_repository_service.rb]: Oyyyy maybe not right now.

File: app/features/configuration/configuration_controller.rb (hunk 1 above)
Comment (AndrewMcBurney) [reply app/features/configuration/configuration_controller.rb]: So, I'm not sure where we actually use the `clone_user_email`. I was looking through [the code where we pre-populate the email](https://github.com/fastlane/ci/blob/master/app/features/login/login_controller.rb#L39) - but we actually get that email from the API token itself. Should we just remove the `*_user_email` environment variables?

I can't see where they're being used elsewhere.

File: app/features/onboarding/onboarding_controller.rb (hunk 3 above)
Comment (AndrewMcBurney) [reply app/features/onboarding/onboarding_controller.rb]: Sorry, I don't really follow. Could you please clarify?

**Comment by AndrewMcBurney** [comment]
Would you like this documentation as part of the onboarding experience (i.e., in HTML), or as part of some markdown document in the repo?

File: app/features/onboarding/onboarding_controller.rb (hunk 3 above)
Comment (taquitos) [reply app/features/onboarding/onboarding_controller.rb]: we aren't really clear about the purpose of `params[:clone_user_api_token]`. I was thinking we no longer needed it because we should be cloning the config repo using the bot's api_token, instead of using a different `clone_user_api_token`. 

We can do that clone once the bot is invited to the repo and the bot accepts the invitation too. That's the invitation dance I was referring to 👯‍♂️👯

**Comment by taquitos** [comment]
> Would you like this documentation as part of the onboarding experience (i.e., in HTML), or as part of some markdown document in the repo?

I think documentation for engineers who need to update the logic in the future, and also really nice on boarding steps too. So I guess, both 🙃

File: app/features/onboarding/onboarding_controller.rb (hunk 3 above)
Comment (AndrewMcBurney) [reply app/features/onboarding/onboarding_controller.rb]: But we still need to validate the token that is used to invite the bot user is 40 characters, and has the correct scopes - right?

Comment (taquitos) [reply app/features/onboarding/onboarding_controller.rb]: Yup 💯

Comment (AndrewMcBurney) [reply app/features/onboarding/onboarding_controller.rb]: I think the confusing thing right now is the naming of `clone_user_api_token`. Should we name it something like - `REPO_USER_API_TOKEN` (probably not the best name, but just throwing a suggestion out there).

Comment (AndrewMcBurney) [reply app/features/onboarding/onboarding_controller.rb]: Could this potentially be done in another PR - so that we have the initial fix for the onboarding issues merged ASAP for alpha users, and then clarify the nomenclature at a later time? 
Thoughts?

Comment (taquitos) [reply app/features/onboarding/onboarding_controller.rb]: Maybe even `INITIAL_ONBOARDING_USER_API_TOKEN`, thoughts?

Comment (taquitos) [reply app/features/onboarding/onboarding_controller.rb]: Yeah, good idea 👍

Comment (AndrewMcBurney) [reply app/features/onboarding/onboarding_controller.rb]: I like that idea. I'll make the changes to this PR when I get off work this evening.

**Comment by freak4pc** [comment]
Just reporting since was trying to use this branch - 
It seems I might've set the wrong PAT (not sure TBH). It's now stuck in a crash loop of "Unauthorized", instead of just not storing that token if it fails authorization:

b665e26c-1c9e-4ee0-b8c2-ef9a46483661

 
51d0cffc-b3b7-46e8-b76b-59589a36ea79

**Comment by taquitos** [comment]
@AndrewMcBurney can you try running `fastlane rspec_me` and `fastlane rubocop` in the ci directory? I see the failure in CI and want to config you see the same:


```
An error occurred while loading ./spec/dashboard_controller_spec.rb.
Failure/Error: require [1;31m"sinatra/flash[1;31m"

LoadError:
cannot load such file -- sinatra/flash
# ./app/shared/controller_base.rb:4:in `require'
# ./app/shared/controller_base.rb:4:in `'
# ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
# ./app/shared/authenticated_controller_base.rb:2:in `'
# ./app/features/dashboard/dashboard_controller.rb:1:in `require_relative'
# ./app/features/dashboard/dashboard_controller.rb:1:in `'
# ./spec/dashboard_controller_spec.rb:2:in `require'
# ./spec/dashboard_controller_spec.rb:2:in `'

An error occurred while loading ./spec/notification_controller_spec.rb.
Failure/Error: require [1;31m"sinatra/flash[1;31m"

LoadError:
cannot load such file -- sinatra/flash
# ./app/shared/controller_base.rb:4:in `require'
# ./app/shared/controller_base.rb:4:in `'
# ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
# ./app/shared/authenticated_controller_base.rb:2:in `'
# ./app/features/notifications/notifications_controller.rb:1:in `require_relative'
# ./app/features/notifications/notifications_controller.rb:1:in `'
# ./spec/notification_controller_spec.rb:2:in `require'
# ./spec/notification_controller_spec.rb:2:in `'

Finished in 0.00038 seconds (files took 2.78 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #459.1
[Coveralls] [4mhttps://coveralls.io/jobs/35625627
Coverage is at 37.33%.
Coverage report sent to Coveralls.

[10:26:53]: fastlane finished with errors
[10:26:53]: Exit status of command 'cd ..;bundle exec rspec' was 1 instead of 0.
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.5-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

An error occurred while loading ./spec/dashboard_controller_spec.rb.
Failure/Error: require [1;31m"sinatra/flash[1;31m"

LoadError:
cannot load such file -- sinatra/flash
# ./app/shared/controller_base.rb:4:in `require'
# ./app/shared/controller_base.rb:4:in `'
# ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
# ./app/shared/authenticated_controller_base.rb:2:in `'
# ./app/features/dashboard/dashboard_controller.rb:1:in `require_relative'
# ./app/features/dashboard/dashboard_controller.rb:1:in `'
# ./spec/dashboard_controller_spec.rb:2:in `require'
# ./spec/dashboard_controller_spec.rb:2:in `'

An error occurred while loading ./spec/notification_controller_spec.rb.
Failure/Error: require [1;31m"sinatra/flash[1;31m"

LoadError:
cannot load such file -- sinatra/flash
# ./app/shared/controller_base.rb:4:in `require'
# ./app/shared/controller_base.rb:4:in `'
# ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
# ./app/shared/authenticated_controller_base.rb:2:in `'
# ./app/features/notifications/notifications_controller.rb:1:in `require_relative'
# ./app/features/notifications/notifications_controller.rb:1:in `'
# ./spec/notification_controller_spec.rb:2:in `require'
# ./spec/notification_controller_spec.rb:2:in `'
```

**Comment by taquitos** [comment]
Will need to manually test this flow tomorrow.

**Comment by taquitos** [comment]
@AndrewMcBurney, let's merge master into this so that you pick up the most recent bug fixes for git repo auth changes.

File: app/services/configuration_repository_service.rb [hunk 10]
```diff
@@ -170,6 +263,33 @@ def remote_file_a_json_array?(file_path)
     # @!group String Helpers
     #####################################################
 
+    # The login of the fastlane.ci bot account
+    #
+    # @return [String]
+    def bot_user_login
+      github_action(bot_user_client) do
+        return bot_user_client.login
```
Comment (snatchev) [inline app/services/configuration_repository_service.rb]: Explicit returns inside blocks are not okay. I think we should have a rubocop rule to disallow this. AFAIK, this return exits the function, and not the block.

File: app/services/configuration_repository_service.rb [hunk 11]
```diff
@@ -9,25 +9,36 @@ class ConfigurationRepositoryService
...
+    #
+    #   i.   Creates the remote repository
+    #   ii.  Adds the bot user as a collaborator and accepts the invitation as
+    #        the bot user
+    #   iii. Creates the necessary remote configuration files as the bot user
+    #
+    def setup_private_configuration_repo
+      create_private_remote_configuration_repo
+      add_bot_user_as_collaborator
+      create_remote_configuration_files
```
Comment (snatchev) [inline app/services/configuration_repository_service.rb]: Would love to see some tests for this behavior.

File: app/services/configuration_repository_service.rb (hunk 10 above)
Comment (taquitos) [reply app/services/configuration_repository_service.rb]: Oh yeah, I think we need to use `next bot_user_client.login`

Comment (snatchev) [reply app/services/configuration_repository_service.rb]: Why not just `bot_user_client.login`? I think this syntax is a bit confusing. I think the block should also yield the client passed in.

Something like:
```ruby
github_action(bot_user_client) do |client|
  client.login
end
```

File: app/services/configuration_repository_service.rb (hunk 11 above)
Comment (AndrewMcBurney) [reply app/services/configuration_repository_service.rb]: You're welcome to write them. Stubbing out octokit and verifying remote GitHub files are written from an external collaborater (just added) to a private remote GitHub repository (just created) is a non-trivial task.

**Comment by snatchev** [comment]
I was able to complete the onboarding with some success. There does seem to be a synchronicity problem here:
https://github.com/fastlane/ci/pull/661/files#diff-7f1f37a512473c728fda7e56977fbdeeR38

It looks like `add_bot_user_as_collaborator` may be called before the repo is actually created (since it maybe async on github's side)

This lead to a permissions error when we try to add the bot user.

**Comment by AndrewMcBurney** [comment]
@taquitos, I'm not sure why rspec and rubocop are failing. 🤔Locally I haven't encountered any issues.

File: app/services/configuration_repository_service.rb (hunk 11 above)
Comment (AndrewMcBurney) [reply app/services/configuration_repository_service.rb]: I'll need to stub out a fair bit of octokit and the GitHub API (requests, responses). I might not get to it until tomorrow, but I'll try to write a lot of reusable helpers so that stubbing the GitHub API for other tests is easy too.

**Comment by taquitos** [comment]
@AndrewMcBurney it's definitely not your fault, I think the fix is here: https://github.com/fastlane/ci/pull/703 
If running the lanes locally works, you're 💯

File: app/services/configuration_repository_service.rb (hunk 11 above)
Comment (taquitos) [reply app/services/configuration_repository_service.rb]: Oh and also, don't worry about tests in this PR, I think we should just make sure it works in a clean environment, merge, and then add those tests I mentioned above.
