### PR TITLE
Use Faraday::Request::Retry to prevent crashes due to poor Internet connectivity

### LINKED ISSUE #798: Intermittent connection error causes server to become unstable
`[2018-05-02 17:10:06] DEBUG GitHubService:  Failed to open TCP connection to api.github.com:443 (getaddrinfo: nodename nor servname provided, or not known)`

`[2018-05-02 17:12:37] ERROR CheckForNewCommitsOnGithubWorker:  [FastlaneCI::CheckForNewCommitsOnGithubWorker Exception], work unit caused exception: Failed to open TCP connection to api.github.com:443 (getaddrinfo: nodename nor servname provided, or not known): 
`

### PR DESCRIPTION
**Pull request by minuscorp**
Fixes #798

### CODE REVIEW

File: app/shared/models/git_repo.rb [hunk 1]
```diff
@@ -87,6 +88,21 @@ def pushes_disabled?
       def load_octokit_cache_stack
         @stack ||= Faraday::RackBuilder.new do |builder|
           builder.use(Faraday::HttpCache, serializer: Marshal, shared_cache: false)
+          # In order to have access to SocketError and ETIMEDOUT exceptions.
+          require "socket"
+          require "net/http"
+          builder.use(Faraday::Request::Retry,
```
Comment (taquitos) [inline app/shared/models/git_repo.rb]: Instead of applying that logic here, I think we should improve the retry logic here: https://github.com/fastlane/ci/blob/master/app/shared/github_handler.rb#L36

That way we don't have multiple layers doing their own retry/backoff logic. 
It's better that we have custom control over how this works in 1 single place.

File: app/shared/github_handler.rb [hunk 2]
```diff
@@ -42,6 +44,24 @@ def self.included(klass)
 
     def github_action(client, &block)
       if client.kind_of?(Octokit::Client)
+        # Inject Faraday::Request::Retry to the client if necessary
+        unless client.middleware.handlers.include?(Faraday::Request::Retry)
```
Comment (taquitos) [inline app/shared/github_handler.rb]: I think it could be worthwhile to pull this out into a separate method instead of inline in the `github_action` method.

File: app/shared/github_handler.rb [hunk 3]
```diff
@@ -42,6 +44,24 @@ def self.included(klass)
...
+          middleware_dup = client.middleware.dup
+          client.middleware = middleware_dup
+          client.middleware.insert_before(Faraday::Adapter::NetHttp,
+                                          Faraday::Request::Retry,
+                                          max: 1000,
+                                          interval: 0.05,
```
Comment (taquitos) [inline app/shared/github_handler.rb]: I wonder if a larger interval value would be better.

File: app/shared/github_handler.rb [hunk 4]
```diff
@@ -42,6 +44,24 @@ def self.included(klass)
 
     def github_action(client, &block)
       if client.kind_of?(Octokit::Client)
+        # Inject Faraday::Request::Retry to the client if necessary
+        unless client.middleware.handlers.include?(Faraday::Request::Retry)
+          middleware_dup = client.middleware.dup
+          client.middleware = middleware_dup
+          client.middleware.insert_before(Faraday::Adapter::NetHttp,
```
Comment (AndrewMcBurney) [inline app/shared/github_handler.rb]: This is a style nitpick, but could you please put the first parameter on a new line, and indent the parameters 2 spaces out?

i.e.,

```ruby
client.middleware.insert_before(
  Faraday::Adapter::NetHttp,
  Faraday::Request::Retry,
  # ...
)
```

File: app/shared/github_handler.rb [hunk 5]
```diff
@@ -42,6 +44,8 @@ def self.included(klass)
 
     def github_action(client, &block)
       if client.kind_of?(Octokit::Client)
+        # Inject Faraday::Request::Retry to the client if necessary
+        client = inject_retry_middleware(client)
```
Comment (taquitos) [inline app/shared/github_handler.rb]: ❤️

File: app/shared/github_handler.rb [hunk 6]
```diff
@@ -97,5 +101,30 @@ def github_action(client, &block)
...
+    private
+
+    def inject_retry_middleware(client)
+      unless client.middleware.handlers.include?(Faraday::Request::Retry)
+        middleware_dup = client.middleware.dup
+        client.middleware = middleware_dup
+        client.middleware.insert_before(
+          Faraday::Adapter::NetHttp,
+          Faraday::Request::Retry,
+          max: 1000,
```
Comment (taquitos) [inline app/shared/github_handler.rb]: I think max should be lower here. We probably shouldn't go nuts since 1000 tries + exponential backoff means we'll never stop retrying. I think 3 tries is enough, then we'll need to catch the resulting exception.

Comment (minuscorp) [reply app/shared/github_handler.rb]: Fair enough! Will change!
