### PR TITLE
Make Bundler load Project's Gemfile dependencies

### LINKED ISSUE #674: Builds are failing due to missing dependencies that exist in gemfile
build http://mydoghatestechnology.com/projects_erb/32903571-271e-4c87-9b32-11df3c82d5aa/builds/461
failed because of a missing gem that is referenced. Locally, the build works fine. It also works fine on the build machine if I `bundle install` there in a terminal and run `be fastlane rspec_me`
So I think our Bundler environment isolation isn't working as expected, or something else is going on.

```
# Logfile created on 2018-04-15 15:45:55 -0700 by logger.rb/56438
[15:45:55]: Driving the lane 'rspec_me' 🚀
[15:45:55]: ----------------------------------
[15:45:55]: --- Step: cd ..;bundle install ---
[15:45:55]: ----------------------------------
[15:45:55]: $ cd ..;bundle install
[15:45:55]: ▸ Running `bundle install` with bundler 1.16.1
[15:45:55]: ▸ Found no changes, using resolution from the lockfile
[15:45:55]: ▸ Using rake 12.3.1
[15:45:55]: ▸ 0: rake (12.3.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rake-12.3.1.gemspec
[15:45:55]: ▸ Using CFPropertyList 3.0.0
[15:45:55]: ▸ 0: CFPropertyList (3.0.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/CFPropertyList-3.0.0.gemspec
[15:45:55]: ▸ Using abstract_type 0.0.7
[15:45:55]: ▸ 0: abstract_type (0.0.7) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/abstract_type-0.0.7.gemspec
[15:45:55]: ▸ Using ice_nine 0.11.2
[15:45:55]: ▸ 0: ice_nine (0.11.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/ice_nine-0.11.2.gemspec
[15:45:55]: ▸ Using thread_safe 0.3.6
[15:45:55]: ▸ 0: thread_safe (0.3.6) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/thread_safe-0.3.6.gemspec
[15:45:55]: ▸ Using memoizable 0.4.2
[15:45:55]: ▸ 0: memoizable (0.4.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/memoizable-0.4.2.gemspec
[15:45:55]: ▸ Using adamantium 0.2.0
[15:45:55]: ▸ 0: adamantium (0.2.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/adamantium-0.2.0.gemspec
[15:45:55]: ▸ Using public_suffix 2.0.5
[15:45:55]: ▸ 0: public_suffix (2.0.5) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/public_suffix-2.0.5.gemspec
[15:45:55]: ▸ Using addressable 2.5.2
[15:45:55]: ▸ 0: addressable (2.5.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/addressable-2.5.2.gemspec
[15:45:55]: ▸ Using ast 2.4.0
[15:45:55]: ▸ 0: ast (2.4.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/ast-2.4.0.gemspec
[15:45:55]: ▸ Using atomos 0.1.2
[15:45:55]: ▸ 0: atomos (0.1.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/atomos-0.1.2.gemspec
[15:45:55]: ▸ Using babosa 1.0.2
[15:45:55]: ▸ 0: babosa (1.0.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/babosa-1.0.2.gemspec
[15:45:55]: ▸ Using backports 3.11.1
[15:45:55]: ▸ 0: backports (3.11.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/backports-3.11.1.gemspec
[15:45:55]: ▸ Using bcrypt 3.1.11
[15:45:55]: ▸ 0: bcrypt (3.1.11) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/bcrypt-3.1.11.gemspec
[15:45:55]: ▸ Using bundler 1.16.1
[15:45:55]: ▸ 0: bundler (1.16.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/bundler-1.16.1.gemspec
[15:45:55]: ▸ Using byebug 10.0.2
[15:45:55]: ▸ 0: byebug (10.0.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/byebug-10.0.2.gemspec
[15:45:55]: ▸ Using claide 1.0.2
[15:45:55]: ▸ 0: claide (1.0.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/claide-1.0.2.gemspec
[15:45:55]: ▸ Using coderay 1.1.2
[15:45:55]: ▸ 0: coderay (1.1.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/coderay-1.1.2.gemspec
[15:45:55]: ▸ Using colored 1.2
[15:45:55]: ▸ 0: colored (1.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/colored-1.2.gemspec
[15:45:55]: ▸ Using colored2 3.1.2
[15:45:55]: ▸ 0: colored2 (3.1.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/colored2-3.1.2.gemspec
[15:45:55]: ▸ Using highline 1.7.10
[15:45:55]: ▸ 0: highline (1.7.10) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/highline-1.7.10.gemspec
[15:45:55]: ▸ Using commander-fastlane 4.4.6
[15:45:55]: ▸ 0: commander-fastlane (4.4.6) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/commander-fastlane-4.4.6.gemspec
[15:45:55]: ▸ Using equalizer 0.0.11
[15:45:55]: ▸ 0: equalizer (0.0.11) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/equalizer-0.0.11.gemspec
[15:45:55]: ▸ Using concord 0.1.5
[15:45:55]: ▸ 0: concord (0.1.5) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/concord-0.1.5.gemspec
[15:45:55]: ▸ Using json 2.1.0
[15:45:55]: ▸ 0: json (2.1.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/json-2.1.0.gemspec
[15:45:55]: ▸ Using docile 1.1.5
[15:45:55]: ▸ 0: docile (1.1.5) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/docile-1.1.5.gemspec
[15:45:55]: ▸ Using simplecov-html 0.10.2
[15:45:55]: ▸ 0: simplecov-html (0.10.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/simplecov-html-0.10.2.gemspec
[15:45:55]: ▸ Using simplecov 0.14.1
[15:45:55]: ▸ 0: simplecov (0.14.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/simplecov-0.14.1.gemspec
[15:45:55]: ▸ Using tins 1.16.3
[15:45:55]: ▸ 0: tins (1.16.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/tins-1.16.3.gemspec
[15:45:55]: ▸ Using term-ansicolor 1.6.0
[15:45:55]: ▸ 0: term-ansicolor (1.6.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/term-ansicolor-1.6.0.gemspec
[15:45:55]: ▸ Using thor 0.19.4
[15:45:55]: ▸ 0: thor (0.19.4) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/thor-0.19.4.gemspec
[15:45:55]: ▸ Using coveralls 0.8.21
[15:45:55]: ▸ 0: coveralls (0.8.21) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/coveralls-0.8.21.gemspec
[15:45:55]: ▸ Using daemons 1.2.6
[15:45:55]: ▸ 0: daemons (1.2.6) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/daemons-1.2.6.gemspec
[15:45:55]: ▸ Using declarative 0.0.10
[15:45:55]: ▸ 0: declarative (0.0.10) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/declarative-0.0.10.gemspec
[15:45:55]: ▸ Using declarative-option 0.1.0
[15:45:55]: ▸ 0: declarative-option (0.1.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/declarative-option-0.1.0.gemspec
[15:45:55]: ▸ Using diff-lcs 1.3
[15:45:55]: ▸ 0: diff-lcs (1.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/diff-lcs-1.3.gemspec
[15:45:55]: ▸ Using digest-crc 0.4.1
[15:45:55]: ▸ 0: digest-crc (0.4.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/digest-crc-0.4.1.gemspec
[15:45:55]: ▸ Using unf_ext 0.0.7.5
[15:45:55]: ▸ 0: unf_ext (0.0.7.5) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/unf_ext-0.0.7.5.gemspec
[15:45:55]: ▸ Using unf 0.1.4
[15:45:55]: ▸ 0: unf (0.1.4) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/unf-0.1.4.gemspec
[15:45:55]: ▸ Using domain_name 0.5.20170404
[15:45:55]: ▸ 0: domain_name (0.5.20170404) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/domain_name-0.5.20170404.gemspec
[15:45:55]: ▸ Using dotenv 2.2.1
[15:45:55]: ▸ 0: dotenv (2.2.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/dotenv-2.2.1.gemspec
[15:45:55]: ▸ Using equatable 0.5.0
[15:45:55]: ▸ 0: equatable (0.5.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/equatable-0.5.0.gemspec
[15:45:55]: ▸ Using tzinfo 1.2.5
[15:45:55]: ▸ 0: tzinfo (1.2.5) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/tzinfo-1.2.5.gemspec
[15:45:55]: ▸ Using et-orbi 1.1.0
[15:45:55]: ▸ 0: et-orbi (1.1.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/et-orbi-1.1.0.gemspec
[15:45:55]: ▸ Using eventmachine 1.2.5
[15:45:55]: ▸ 0: eventmachine (1.2.5) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/eventmachine-1.2.5.gemspec
[15:45:55]: ▸ Using excon 0.62.0
[15:45:55]: ▸ 0: excon (0.62.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/excon-0.62.0.gemspec
[15:45:55]: ▸ Using multipart-post 2.0.0
[15:45:55]: ▸ 0: multipart-post (2.0.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/multipart-post-2.0.0.gemspec
[15:45:55]: ▸ Using faraday 0.14.0
[15:45:55]: ▸ 0: faraday (0.14.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/faraday-0.14.0.gemspec
[15:45:55]: ▸ Using http-cookie 1.0.3
[15:45:55]: ▸ 0: http-cookie (1.0.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/http-cookie-1.0.3.gemspec
[15:45:55]: ▸ Using faraday-cookie_jar 0.0.6
[15:45:55]: ▸ 0: faraday-cookie_jar (0.0.6) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/faraday-cookie_jar-0.0.6.gemspec
[15:45:55]: ▸ Using faraday-http-cache 2.0.0
[15:45:55]: ▸ 0: faraday-http-cache (2.0.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/faraday-http-cache-2.0.0.gemspec
[15:45:55]: ▸ Using faraday_middleware 0.12.2
[15:45:55]: ▸ 0: faraday_middleware (0.12.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/faraday_middleware-0.12.2.gemspec
[15:45:55]: ▸ Using parser 2.4.0.2
[15:45:55]: ▸ 0: parser (2.4.0.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/parser-2.4.0.2.gemspec
[15:45:55]: ▸ Using procto 0.0.3
[15:45:55]: ▸ 0: procto (0.0.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/procto-0.0.3.gemspec
[15:45:55]: ▸ Using unparser 0.2.7
[15:45:55]: ▸ 0: unparser (0.2.7) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/unparser-0.2.7.gemspec
[15:45:55]: ▸ Using fastfile-parser 0.0.0 from https://github.com/fastlane/fastfile-parser (at master@a9707d8)
[15:45:55]: ▸ 0: fastfile-parser (0.0.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastfile-parser-a9707d87eb6b/fastfile-parser.gemspec
[15:45:55]: ▸ Using fastimage 2.1.1
[15:45:55]: ▸ 0: fastimage (2.1.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/fastimage-2.1.1.gemspec
[15:45:55]: ▸ Using gh_inspector 1.1.3
[15:45:55]: ▸ 0: gh_inspector (1.1.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/gh_inspector-1.1.3.gemspec
[15:45:55]: ▸ Using jwt 2.1.0
[15:45:55]: ▸ 0: jwt (2.1.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/jwt-2.1.0.gemspec
[15:45:55]: ▸ Using little-plugger 1.1.4
[15:45:55]: ▸ 0: little-plugger (1.1.4) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/little-plugger-1.1.4.gemspec
[15:45:55]: ▸ Using multi_json 1.13.1
[15:45:55]: ▸ 0: multi_json (1.13.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/multi_json-1.13.1.gemspec
[15:45:55]: ▸ Using logging 2.2.2
[15:45:55]: ▸ 0: logging (2.2.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/logging-2.2.2.gemspec
[15:45:55]: ▸ Using memoist 0.16.0
[15:45:55]: ▸ 0: memoist (0.16.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/memoist-0.16.0.gemspec
[15:45:55]: ▸ Using os 0.9.6
[15:45:55]: ▸ 0: os (0.9.6) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/os-0.9.6.gemspec
[15:45:55]: ▸ Using signet 0.8.1
[15:45:55]: ▸ 0: signet (0.8.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/signet-0.8.1.gemspec
[15:45:55]: ▸ Using googleauth 0.6.2
[15:45:55]: ▸ 0: googleauth (0.6.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/googleauth-0.6.2.gemspec
[15:45:55]: ▸ Using httpclient 2.8.3
[15:45:55]: ▸ 0: httpclient (2.8.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/httpclient-2.8.3.gemspec
[15:45:55]: ▸ Using mime-types-data 3.2016.0521
[15:45:55]: ▸ 0: mime-types-data (3.2016.0521) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/mime-types-data-3.2016.0521.gemspec
[15:45:55]: ▸ Using mime-types 3.1
[15:45:55]: ▸ 0: mime-types (3.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/mime-types-3.1.gemspec
[15:45:55]: ▸ Using uber 0.1.0
[15:45:55]: ▸ 0: uber (0.1.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/uber-0.1.0.gemspec
[15:45:55]: ▸ Using representable 3.0.4
[15:45:55]: ▸ 0: representable (3.0.4) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/representable-3.0.4.gemspec
[15:45:55]: ▸ Using retriable 3.1.1
[15:45:55]: ▸ 0: retriable (3.1.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/retriable-3.1.1.gemspec
[15:45:55]: ▸ Using google-api-client 0.13.6
[15:45:55]: ▸ 0: google-api-client (0.13.6) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/google-api-client-0.13.6.gemspec
[15:45:55]: ▸ Using mini_magick 4.5.1
[15:45:55]: ▸ 0: mini_magick (4.5.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/mini_magick-4.5.1.gemspec
[15:45:55]: ▸ Using multi_xml 0.6.0
[15:45:55]: ▸ 0: multi_xml (0.6.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/multi_xml-0.6.0.gemspec
[15:45:55]: ▸ Using plist 3.4.0
[15:45:55]: ▸ 0: plist (3.4.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/plist-3.4.0.gemspec
[15:45:55]: ▸ Using rubyzip 1.2.1
[15:45:55]: ▸ 0: rubyzip (1.2.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rubyzip-1.2.1.gemspec
[15:45:56]: ▸ Using security 0.1.3
[15:45:56]: ▸ 0: security (0.1.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/security-0.1.3.gemspec
[15:45:56]: ▸ Using naturally 2.1.0
[15:45:56]: ▸ 0: naturally (2.1.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/naturally-2.1.0.gemspec
[15:45:56]: ▸ Using simctl 1.6.3
[15:45:56]: ▸ 0: simctl (1.6.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/simctl-1.6.3.gemspec
[15:45:56]: ▸ Using slack-notifier 2.3.2
[15:45:56]: ▸ 0: slack-notifier (2.3.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/slack-notifier-2.3.2.gemspec
[15:45:56]: ▸ Using terminal-notifier 1.8.0
[15:45:56]: ▸ 0: terminal-notifier (1.8.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/terminal-notifier-1.8.0.gemspec
[15:45:56]: ▸ Using unicode-display_width 1.3.0
[15:45:56]: ▸ 0: unicode-display_width (1.3.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/unicode-display_width-1.3.0.gemspec
[15:45:56]: ▸ Using terminal-table 1.8.0
[15:45:56]: ▸ 0: terminal-table (1.8.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/terminal-table-1.8.0.gemspec
[15:45:56]: ▸ Using tty-screen 0.6.4
[15:45:56]: ▸ 0: tty-screen (0.6.4) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/tty-screen-0.6.4.gemspec
[15:45:56]: ▸ Using tty-cursor 0.5.0
[15:45:56]: ▸ 0: tty-cursor (0.5.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/tty-cursor-0.5.0.gemspec
[15:45:56]: ▸ Using tty-spinner 0.8.0
[15:45:56]: ▸ 0: tty-spinner (0.8.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/tty-spinner-0.8.0.gemspec
[15:45:56]: ▸ Using word_wrap 1.0.0
[15:45:56]: ▸ 0: word_wrap (1.0.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/word_wrap-1.0.0.gemspec
[15:45:56]: ▸ Using nanaimo 0.2.5
[15:45:56]: ▸ 0: nanaimo (0.2.5) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/nanaimo-0.2.5.gemspec
[15:45:56]: ▸ Using xcodeproj 1.5.7
[15:45:56]: ▸ 0: xcodeproj (1.5.7) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/xcodeproj-1.5.7.gemspec
[15:45:56]: ▸ Using rouge 2.0.7
[15:45:56]: ▸ 0: rouge (2.0.7) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rouge-2.0.7.gemspec
[15:45:56]: ▸ Using xcpretty 0.2.8
[15:45:56]: ▸ 0: xcpretty (0.2.8) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/xcpretty-0.2.8.gemspec
[15:45:56]: ▸ Using xcpretty-travis-formatter 1.0.0
[15:45:56]: ▸ 0: xcpretty-travis-formatter (1.0.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/xcpretty-travis-formatter-1.0.0.gemspec
[15:45:56]: ▸ Using fastlane 2.89.0 from https://github.com/fastlane/fastlane (at master@c579921)
[15:45:56]: ▸ 0: fastlane (2.89.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/fastlane-c579921dcf7a/fastlane.gemspec
[15:45:56]: ▸ Using websocket-extensions 0.1.3
[15:45:56]: ▸ 0: websocket-extensions (0.1.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/websocket-extensions-0.1.3.gemspec
[15:45:56]: ▸ Using websocket-driver 0.7.0
[15:45:56]: ▸ 0: websocket-driver (0.7.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/websocket-driver-0.7.0.gemspec
[15:45:56]: ▸ Using faye-websocket 0.10.7
[15:45:56]: ▸ 0: faye-websocket (0.10.7) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/faye-websocket-0.10.7.gemspec
[15:45:56]: ▸ Using git 1.3.0
[15:45:56]: ▸ 0: git (1.3.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/git-1.3.0.gemspec
[15:45:56]: ▸ Using google-cloud-env 1.0.1
[15:45:56]: ▸ 0: google-cloud-env (1.0.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/google-cloud-env-1.0.1.gemspec
[15:45:56]: ▸ Using google-cloud-core 1.2.0
[15:45:56]: ▸ 0: google-cloud-core (1.2.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/google-cloud-core-1.2.0.gemspec
[15:45:56]: ▸ Using google-cloud-storage 1.5.0
[15:45:56]: ▸ 0: google-cloud-storage (1.5.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/google-cloud-storage-1.5.0.gemspec
[15:45:56]: ▸ Using method_source 0.9.0
[15:45:56]: ▸ 0: method_source (0.9.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/method_source-0.9.0.gemspec
[15:45:56]: ▸ Using mustermann 1.0.2
[15:45:56]: ▸ 0: mustermann (1.0.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/mustermann-1.0.2.gemspec
[15:45:56]: ▸ Using sawyer 0.8.1
[15:45:56]: ▸ 0: sawyer (0.8.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/sawyer-0.8.1.gemspec
[15:45:56]: ▸ Using octokit 4.8.0
[15:45:56]: ▸ 0: octokit (4.8.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/octokit-4.8.0.gemspec
[15:45:56]: ▸ Using parallel 1.12.1
[15:45:56]: ▸ 0: parallel (1.12.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/parallel-1.12.1.gemspec
[15:45:56]: ▸ Using tty-color 0.4.2
[15:45:56]: ▸ 0: tty-color (0.4.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/tty-color-0.4.2.gemspec
[15:45:56]: ▸ Using pastel 0.7.2
[15:45:56]: ▸ 0: pastel (0.7.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/pastel-0.7.2.gemspec
[15:45:56]: ▸ Using powerpack 0.1.1
[15:45:56]: ▸ 0: powerpack (0.1.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/powerpack-0.1.1.gemspec
[15:45:56]: ▸ Using pry 0.11.3
[15:45:56]: ▸ 0: pry (0.11.3) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/pry-0.11.3.gemspec
[15:45:56]: ▸ Using pry-byebug 3.6.0
[15:45:56]: ▸ 0: pry-byebug (3.6.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/pry-byebug-3.6.0.gemspec
[15:45:56]: ▸ Using rack 2.0.4
[15:45:56]: ▸ 0: rack (2.0.4) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rack-2.0.4.gemspec
[15:45:56]: ▸ Using rack-protection 2.0.1
[15:45:56]: ▸ 0: rack-protection (2.0.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rack-protection-2.0.1.gemspec
[15:45:56]: ▸ Using rack-test 1.0.0
[15:45:56]: ▸ 0: rack-test (1.0.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rack-test-1.0.0.gemspec
[15:45:56]: ▸ Using rainbow 3.0.0
[15:45:56]: ▸ 0: rainbow (3.0.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rainbow-3.0.0.gemspec
[15:45:56]: ▸ Using rspec-support 3.7.1
[15:45:56]: ▸ 0: rspec-support (3.7.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rspec-support-3.7.1.gemspec
[15:45:56]: ▸ Using rspec-core 3.7.1
[15:45:56]: ▸ 0: rspec-core (3.7.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rspec-core-3.7.1.gemspec
[15:45:56]: ▸ Using rspec-expectations 3.7.0
[15:45:56]: ▸ 0: rspec-expectations (3.7.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rspec-expectations-3.7.0.gemspec
[15:45:56]: ▸ Using rspec-mocks 3.7.0
[15:45:56]: ▸ 0: rspec-mocks (3.7.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rspec-mocks-3.7.0.gemspec
[15:45:56]: ▸ Using rspec 3.7.0
[15:45:56]: ▸ 0: rspec (3.7.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rspec-3.7.0.gemspec
[15:45:56]: ▸ Using ruby-progressbar 1.9.0
[15:45:56]: ▸ 0: ruby-progressbar (1.9.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/ruby-progressbar-1.9.0.gemspec
[15:45:56]: ▸ Using rubocop 0.52.1
[15:45:56]: ▸ 0: rubocop (0.52.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rubocop-0.52.1.gemspec
[15:45:56]: ▸ Using rufus-scheduler 3.4.2
[15:45:56]: ▸ 0: rufus-scheduler (3.4.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/rufus-scheduler-3.4.2.gemspec
[15:45:56]: ▸ Using tilt 2.0.8
[15:45:56]: ▸ 0: tilt (2.0.8) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/tilt-2.0.8.gemspec
[15:45:56]: ▸ Using sinatra 2.0.1
[15:45:56]: ▸ 0: sinatra (2.0.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/sinatra-2.0.1.gemspec
[15:45:56]: ▸ Using sinatra-contrib 2.0.1
[15:45:56]: ▸ 0: sinatra-contrib (2.0.1) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/sinatra-contrib-2.0.1.gemspec
[15:45:56]: ▸ Using taskqueue 0.0.0 from https://github.com/fastlane/TaskQueue (at master@5b3f459)
[15:45:56]: ▸ 0: taskqueue (0.0.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/taskqueue.gemspec
[15:45:56]: ▸ Using thin 1.7.2
[15:45:56]: ▸ 0: thin (1.7.2) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/thin-1.7.2.gemspec
[15:45:56]: ▸ Using tty-command 0.7.0
[15:45:56]: ▸ 0: tty-command (0.7.0) from /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/tty-command-0.7.0.gemspec
[15:45:56]: ▸ Bundle complete! 23 Gemfile dependencies, 129 gems now installed.
[15:45:56]: ▸ Use `bundle info [gemname]` to see where a bundled gem is installed.
[15:45:56]: -------------------------------------
[15:45:56]: --- Step: cd ..;bundle exec rspec ---
[15:45:56]: -------------------------------------
[15:45:56]: $ cd ..;bundle exec rspec
[15:45:57]: ▸ warning: parser/current is loading parser/ruby23, which recognizes
[15:45:57]: ▸ warning: 2.3.5-compliant syntax, but you are running 2.3.3.
[15:45:57]: ▸ warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
[15:45:57]: ▸ [Coveralls] Set up the SimpleCov formatter.
[15:45:57]: ▸ [Coveralls] Using SimpleCov's default settings.
[15:45:59]: ▸ An error occurred while loading ./spec/dashboard_controller_spec.rb.
[15:45:59]: ▸ Failure/Error: require [1;31m"sinatra/flash[1;31m"
[15:45:59]: ▸ 
[15:45:59]: ▸ LoadError:
[15:45:59]: ▸ cannot load such file -- sinatra/flash
[15:45:59]: ▸ # ./app/shared/controller_base.rb:4:in `require'
[15:45:59]: ▸ # ./app/shared/controller_base.rb:4:in `'
[15:45:59]: ▸ # ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
[15:45:59]: ▸ # ./app/shared/authenticated_controller_base.rb:2:in `'
[15:45:59]: ▸ # ./app/features/dashboard/dashboard_controller.rb:1:in `require_relative'
[15:45:59]: ▸ # ./app/features/dashboard/dashboard_controller.rb:1:in `'
[15:45:59]: ▸ # ./spec/dashboard_controller_spec.rb:2:in `require'
[15:45:59]: ▸ # ./spec/dashboard_controller_spec.rb:2:in `'
[15:45:59]: ▸ An error occurred while loading ./spec/notification_controller_spec.rb.
[15:45:59]: ▸ Failure/Error: require [1;31m"sinatra/flash[1;31m"
[15:45:59]: ▸ 
[15:45:59]: ▸ LoadError:
[15:45:59]: ▸ cannot load such file -- sinatra/flash
[15:45:59]: ▸ # ./app/shared/controller_base.rb:4:in `require'
[15:45:59]: ▸ # ./app/shared/controller_base.rb:4:in `'
[15:45:59]: ▸ # ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
[15:45:59]: ▸ # ./app/shared/authenticated_controller_base.rb:2:in `'
[15:45:59]: ▸ # ./app/features/notifications/notifications_controller.rb:1:in `require_relative'
[15:45:59]: ▸ # ./app/features/notifications/notifications_controller.rb:1:in `'
[15:45:59]: ▸ # ./spec/notification_controller_spec.rb:2:in `require'
[15:45:59]: ▸ # ./spec/notification_controller_spec.rb:2:in `'
[15:45:59]: ▸ Finished in 0.0004 seconds (files took 2.9 seconds to load)
[15:45:59]: ▸ 0 examples, 0 failures, 2 errors occurred outside of examples
[15:45:59]: ▸ [Coveralls] Submitting to https://coveralls.io/api/v1
[15:46:00]: ▸ [Coveralls] Job #461.1
[15:46:00]: ▸ [Coveralls] [4mhttps://coveralls.io/jobs/35630153
[15:46:00]: ▸ Coverage is at 37.33%.
[15:46:00]: ▸ Coverage report sent to Coveralls.
[15:46:01]: Lane Context:
[15:46:01]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"rspec_me"}
[15:46:01]: Exit status of command 'cd ..;bundle exec rspec' was 1 instead of 0.
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.5-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

An error occurred while loading ./spec/dashboard_controller_spec.rb.
Failure/Error: require [1;31m"sinatra/flash[1;31m"

LoadError:
cannot load such file -- sinatra/flash
# ./app/shared/controller_base.rb:4:in `require'
# ./app/shared/controller_base.rb:4:in `'
# ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
# ./app/shared/authenticated_controller_base.rb:2:in `'
# ./app/features/dashboard/dashboard_controller.rb:1:in `require_relative'
# ./app/features/dashboard/dashboard_controller.rb:1:in `'
# ./spec/dashboard_controller_spec.rb:2:in `require'
# ./spec/dashboard_controller_spec.rb:2:in `'

An error occurred while loading ./spec/notification_controller_spec.rb.
Failure/Error: require [1;31m"sinatra/flash[1;31m"

LoadError:
cannot load such file -- sinatra/flash
# ./app/shared/controller_base.rb:4:in `require'
# ./app/shared/controller_base.rb:4:in `'
# ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
# ./app/shared/authenticated_controller_base.rb:2:in `'
# ./app/features/notifications/notifications_controller.rb:1:in `require_relative'
# ./app/features/notifications/notifications_controller.rb:1:in `'
# ./spec/notification_controller_spec.rb:2:in `require'
# ./spec/notification_controller_spec.rb:2:in `'

Finished in 0.0004 seconds (files took 2.9 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #461.1
[Coveralls] [4mhttps://coveralls.io/jobs/35630153
Coverage is at 37.33%.
Coverage report sent to Coveralls.

[15:46:01]: fastlane finished with errors
[15:46:01]: Exit status of command 'cd ..;bundle exec rspec' was 1 instead of 0.
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.5-compliant syntax, but you are running 2.3.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

An error occurred while loading ./spec/dashboard_controller_spec.rb.
Failure/Error: require [1;31m"sinatra/flash[1;31m"

LoadError:
cannot load such file -- sinatra/flash
# ./app/shared/controller_base.rb:4:in `require'
# ./app/shared/controller_base.rb:4:in `'
# ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
# ./app/shared/authenticated_controller_base.rb:2:in `'
# ./app/features/dashboard/dashboard_controller.rb:1:in `require_relative'
# ./app/features/dashboard/dashboard_controller.rb:1:in `'
# ./spec/dashboard_controller_spec.rb:2:in `require'
# ./spec/dashboard_controller_spec.rb:2:in `'

An error occurred while loading ./spec/notification_controller_spec.rb.
Failure/Error: require [1;31m"sinatra/flash[1;31m"

LoadError:
cannot load such file -- sinatra/flash
# ./app/shared/controller_base.rb:4:in `require'
# ./app/shared/controller_base.rb:4:in `'
# ./app/shared/authenticated_controller_base.rb:2:in `require_relative'
# ./app/shared/authenticated_controller_base.rb:2:in `'
# ./app/features/notifications/notifications_controller.rb:1:in `require_relative'
# ./app/features/notifications/notifications_controller.rb:1:in `'
# ./spec/notification_controller_spec.rb:2:in `require'
# ./spec/notification_controller_spec.rb:2:in `'

Finished in 0.0004 seconds (files took 2.9 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples

[Coveralls] Submitting to https://coveralls.io/api/v1
[Coveralls] Job #461.1
[Coveralls] [4mhttps://coveralls.io/jobs/35630153
Coverage is at 37.33%.
Coverage report sent to Coveralls.
```

### PR DESCRIPTION
**Pull request by minuscorp**
Fixes #674

### CODE REVIEW

File: app/features/build_runner/fastlane_build_runner.rb [hunk 1]
```diff
@@ -100,28 +100,41 @@ def run(new_line_block:, completion_block:)
...
+              logger.info("Bundle complete! #{definition.dependencies.count} Gemfile dependencies, installed #{definition.specs.count} gems.")
+              # rubocop:enable Metrics/LineLength
+              Bundler::SharedHelpers.set_bundle_environment
+
+              not_installed = definition.missing_specs
+              if not_installed.any?
+                logger.error("The following gems are missing")
+                not_installed.each { |s| logger.error(" * #{s.name} (#{s.version})") }
+              end
+            rescue Bundler::GemfileNotFound => ex
```
Comment (taquitos) [inline app/features/build_runner/fastlane_build_runner.rb]: let's use `notification_service` here too, here's an example: https://github.com/fastlane/ci/blob/c81ec496cb7f38f5daa8eedc525e17c865509c88/app/shared/models/git_repo.rb#L176
Ideally, we send this notification to the admin of the machine so they can potentially file a bug, or something

Comment (minuscorp) [reply app/features/build_runner/fastlane_build_runner.rb]: Nice! I'll first try to make it work properly but that's a good one!!

Comment (taquitos) [reply app/features/build_runner/fastlane_build_runner.rb]: Cool, there's already a `notification_service` property on the super class 👍

**Comment by minuscorp** [comment]
This is becoming too a dead end. When I success in loading the Gemfile, it fails if there's already the same gem (different version loaded) and I don't see any way to unload the gems of the current process, and bundler seems not to achieve the isolation... I'll try to work on it this evening but is not looking good 😔

**Comment by minuscorp** [comment]
So this is the output of a `Project` with a `Gemfile` that uses the `betterlorem` gem in the lane:
```
# Logfile created on 2018-04-20 00:59:14 +0200 by logger.rb/56438
[00:59:14]: ------------------------------
[00:59:14]: --- Step: default_platform ---
[00:59:14]: ------------------------------
[00:59:14]: gem 'betterlorem' is already installed
[00:59:14]: Driving the lane 'ios test' 🚀
[00:59:14]:
Terra Zabulon, et terra Nephthalim, via maris trans Jordanem, alilæa gentium populus, qui sedebat in.
[00:59:14]: fastlane.tools finished successfully 🎉
```
So the only way that I accomplished this is doing the following:

1. Read and store the state of the CI `Gemfile` and `Gemfile.lock`
2. Inject all dependencies (reject `fastlane`, that we use the CI's version). This make changes in both files in step 1.
3. Install and require the new gems detected from the building repo.
4. Write the original contents to the `Gemfile` and `Gemfile.lock` before finishing (`inject`ing modifies both files).

This works. Is not the **perfect** solution? I don't think so, but I can't make with another solution.

**Comment by taquitos** [comment]
@minuscorp does this merge the dependencies of CI and whatever project is being built?

**Comment by minuscorp** [comment]
This temporally adds dependencies of other projects to the CI (while building) then, CI's original dependencies are restored and installed again.

**Comment by taquitos** [comment]
Ok, let's go with it for now, but ultimately I think we need to actually fork a new process to avoid this approach.
Realistically speaking, we're a mobile ci, so we're mainly seeing this issue because we're running CI for CI. 
During normal usage I don't think people will run into this issue.

**Comment by minuscorp** [comment]
Yep, I know this is super hacky, but while we're attached to the same thread as the CI for the builds I couldn't find any other way to workaround this. In a future the whole fastlane build runner _should_(?) be a `RecreatableTask` with its own scope, where it would be able to grab the CI fastlane dependency, inject it to the build, and install all the other gems (if any)

**Comment by taquitos** [comment]
💯 agree on that. It should be it's own process so there isn't any polluting of lane contexts like we have now, and it would enable us to have better resiliency to crashes and other issues.
Ideally we'd spawn a new process and inject all the dependencies like you said, then use some form of IPC to monitor the build.

File: app/features/build_runner/fastlane_build_runner.rb [hunk 2]
```diff
@@ -98,30 +98,50 @@ def run(new_line_block:, completion_block:)
         # folder, and all the following code works
         # This is needed to load other configuration files, and also find Xcode projects
 
+        original_gemfile = File.open(Bundler.default_gemfile, "rb")
```
Comment (AndrewMcBurney) [inline app/features/build_runner/fastlane_build_runner.rb]: Could we simplify this to:

```ruby
original_gemfile_contents = File.read(Bundler.default_gemfile)
original_lockfile_contents = File.read(Bundler.default_lockfile)
```

File: app/features/build_runner/fastlane_build_runner.rb [hunk 3]
```diff
@@ -153,6 +173,15 @@ def run(new_line_block:, completion_block:)
             artifacts_paths = gather_build_artifact_paths(loggers: [verbose_log, info_log])
 
             return
+          ensure
+            if gemfile_found
```
Comment (AndrewMcBurney) [inline app/features/build_runner/fastlane_build_runner.rb]: Could we simplify this ensure block to:

```ruby
ensure
  return unless gemfile_found
  original_gemfile_contents = File.read(Bundler.default_gemfile)
  original_lockfile_contents = File.read(Bundler.default_lockfile)
end
```

**Comment by minuscorp** [comment]
Thinking out loud, unidirectional IPC -> `IO.pipe`, bidirectional IPC -> `Socket.pair`. This would change a lot of the things as they are designed right now though

**Comment by minuscorp** [comment]
Oh man, just squashed :(

File: app/features/build_runner/fastlane_build_runner.rb (hunk 3 above)
Comment (minuscorp) [reply app/features/build_runner/fastlane_build_runner.rb]: agh, never `return` in a ensure block 😢

Comment (AndrewMcBurney) [reply app/features/build_runner/fastlane_build_runner.rb]: Forgot that, good catch.
