### PR TITLE
Encrypt api token and store in correct ivar

### LINKED ISSUE #544: Unable to check repository status on launch if repo is private
During startup we check to make sure the ci-config repo is in a good state. If it's a private repo, this can fail.

### PR DESCRIPTION
**Pull request by taquitos**
fixes #544 
cc @AndrewMcBurney just a heads up, this was broken due to the unify pr. we worked on. Just wanted to ping you since this is a great thing to see that broke. No hard feelings 😄

### CODE REVIEW

File: app/shared/models/github_provider_credential.rb [hunk 1]
```diff
@@ -30,21 +30,25 @@ def initialize(id: nil, email: nil, full_name: nil, api_token: nil)
       @id = id || SecureRandom.uuid
       @email = email
       @full_name = full_name
-      @api_token = api_token
```
Comment (taquitos) [inline app/shared/models/github_provider_credential.rb]: this used to be `self.api_token=` which called the setter we wrote, so when `@api_token` was swapped, it no longer provided access to the token since we overrode the getter and setter to decrypt and encrypt `@encrypted_api_token` on the fly.

Comment (AndrewMcBurney) [reply app/shared/models/github_provider_credential.rb]: Ahh, my apologies, that makes sense - was an overlook on my part. Thank you for finding the issue and fixing it!

Comment (taquitos) [reply app/shared/models/github_provider_credential.rb]: No worries! It's a tricky one, but really good to learn from!
