### PR TITLE
Handle git errors more gracefully by killing the build and reporting issues

### LINKED ISSUE #543: `Could not parse object` git issue
no idea what this is about

```
[2018-04-03 20:50:29] ERROR GitRepo:  Error resetting and checking out sha: 5f5ea6bdb93a8f73888f1d81a4491a775712d19c from https://github.com/fastlane/ci
[2018-04-03 20:50:29] ERROR GitRepo:  git '--git-dir=/Users/jliebowitz/.fastlane/ci/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/5f5ea6bdb93a8f73888f1d81a4491a775712d19c/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/5f5ea6bdb93a8f73888f1d81a4491a775712d19c' reset '--hard' '5f5ea6bdb93a8f73888f1d81a4491a775712d19c'  2>&1:fatal: Could not parse object '5f5ea6bdb93a8f73888f1d81a4491a775712d19c'.
Thread terminated with exception: git '--git-dir=/Users/jliebowitz/.fastlane/ci/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/5f5ea6bdb93a8f73888f1d81a4491a775712d19c/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/5f5ea6bdb93a8f73888f1d81a4491a775712d19c' reset '--hard' '5f5ea6bdb93a8f73888f1d81a4491a775712d19c'  2>&1:fatal: Could not parse object '5f5ea6bdb93a8f73888f1d81a4491a775712d19c'.
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:562:in `reset'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/base.rb:242:in `reset_hard'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:452:in `block in checkout_commit'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:407:in `block in perform_block'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'
[2018-04-03 20:50:29] DEBUG GitRepo:  Starting commit_changes! https://github.com/fastlane/ci-config-heroku for taquitos@gmail.com
bundler: failed to load command: rackup (/Users/jliebowitz/.rbenv/versions/2.3.3/bin/rackup)
Git::GitExecuteError: git '--git-dir=/Users/jliebowitz/.fastlane/ci/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/5f5ea6bdb93a8f73888f1d81a4491a775712d19c/.git' '--work-tree=/Users/jliebowitz/.fastlane/ci/d02bf494-1290-42a9-bb52-f128afd52cd9/builds/5f5ea6bdb93a8f73888f1d81a4491a775712d19c' reset '--hard' '5f5ea6bdb93a8f73888f1d81a4491a775712d19c'  2>&1:fatal: Could not parse object '5f5ea6bdb93a8f73888f1d81a4491a775712d19c'.
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:562:in `reset'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/base.rb:242:in `reset_hard'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:452:in `block in checkout_commit'
  /Users/jliebowitz/dev/ci/app/shared/models/git_repo.rb:407:in `block in perform_block'
  /Users/jliebowitz/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/TaskQueue-5b3f459be5c4/lib/queue_worker.rb:82:in `block in process'[2018-04-03 20:50:29] DEBUG GitRepo:  Using Clone User credentials with taquitos@gmail.com as author information on https://github.com/fastlane/ci-config-heroku
```

### PR DESCRIPTION
**Pull request by taquitos**
- Handle missing git objects
- Don't attempt a build when git
- Fixes #543

### CODE REVIEW

File: app/features/build_runner/build_runner.rb [hunk 1]
```diff
@@ -91,6 +91,27 @@ def setup
...
+    def fail_build!(start_time:)
+      duration = Time.now - start_time
+      current_build.duration = duration
+      current_build.status = :failure # TODO: also handle failure
+      save_build_status!
+    end
+
+    def run_completed_ensure
+      # Make sure to notify the listeners that the build is over
+      new_row(
```
Comment (taquitos) [inline app/features/build_runner/build_runner.rb]: @KrauseFx is calling `new_row` ok if called from `fail_build!` instead of from the build completion flow? `fastlane_build_runner` won't have connected any outputs AFAICT

File: app/features/build_runner/build_runner.rb [hunk 2]
```diff
@@ -111,22 +132,9 @@ def complete_run(start_time:, artifact_paths: [])
       save_build_status!
     rescue StandardError => ex
       logger.error(ex)
-      duration = Time.now - start_time
-      current_build.duration = duration
-      current_build.status = :failure # TODO: also handle failure
-      save_build_status!
+      fail_build!(start_time: start_time)
```
Comment (taquitos) [inline app/features/build_runner/build_runner.rb]: extracted so we could use it in 2 places

File: app/features/build_runner/build_runner.rb [hunk 3]
```diff
@@ -111,22 +132,9 @@ def complete_run(start_time:, artifact_paths: [])
...
-        FastlaneCI::BuildRunnerOutputRow.new(
-          type: :last_message,
-          message: nil,
-          time: Time.now
-        )
-      )
-      # Remove ourselves from the list of active build runners
-      # to let the garbage collector do its thing
-      Services.build_runner_service.remove_build_runner(build_runner: self)
+      run_completed_ensure
```
Comment (taquitos) [inline app/features/build_runner/build_runner.rb]: same here, extracted for use in 2 places.

File: app/features/build_runner/build_runner.rb [hunk 4]
```diff
@@ -91,6 +91,27 @@ def setup
       not_implemented(__method__)
     end
 
+    def fail_build!(start_time:)
+      duration = Time.now - start_time
+      current_build.duration = duration
+      current_build.status = :failure # TODO: also handle failure
```
Comment (KrauseFx) [inline app/features/build_runner/build_runner.rb]: Is this TODO still relevant then?

File: app/features/build_runner/build_runner.rb (hunk 1 above)
Comment (KrauseFx) [reply app/features/build_runner/build_runner.rb]: I think it should be fine. It is important that `new_row` is called exactly once with `:last_message` no matter if the build suceeded or failed

File: app/features/build_runner/build_runner.rb (hunk 2 above)
Comment (KrauseFx) [reply app/features/build_runner/build_runner.rb]: Ahhh nice catch!!

File: app/features/build_runner/build_runner.rb (hunk 4 above)
Comment (taquitos) [reply app/features/build_runner/build_runner.rb]: OHHH right, ha.

File: app/features/build_runner/build_runner.rb [hunk 5]
```diff
@@ -94,7 +94,7 @@ def setup
     def fail_build!(start_time:)
       duration = Time.now - start_time
       current_build.duration = duration
-      current_build.status = :failure # TODO: also handle failure
+      current_build.status = :failure
```
Comment (KrauseFx) [inline app/features/build_runner/build_runner.rb]: best
